package com.automation.helpers;

public enum KEYS {
    TAG, APPIUM_SERVER_STARTED, DEVICE_ID, PLATFORM, SUB_PLATFORM, PROJECT_PATH, TEST_RESOURCES, REPORT_PATH, DRIVER, FEATURE_FILES_PATH, BROWSER, OS_NAME, APP_URL, STANDALONE_SERVER_PATH, REMOTEWEBDRIVER_BROWSERS;

}
